services:

  postgres-users-db:
    image: postgres:13
    container_name: postgres-users-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: always

  postgres-products-db:
    image: postgres:13
    container_name: postgres-products-db
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - backend
    restart: always

  postgres-orders-db:
    image: postgres:13
    container_name: postgres-orders-db
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - backend
    restart: always

  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-users-db:5432/usersdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend
    depends_on:
      - postgres-users-db
    restart: always

  products-service:
    build: ./products-service
    container_name: products-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-products-db:5432/productsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend
    depends_on:
      - postgres-products-db
    restart: always

  orders-service:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-orders-db:5432/ordersdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend
    depends_on:
      - postgres-orders-db
    restart: always

networks:
  backend:
    driver: bridge
